Ensure that we have tests for all supported platforms

diff --git a/ansible/tests/Makefile b/ansible/tests/Makefile
--- a/ansible/tests/Makefile
+++ b/ansible/tests/Makefile
@@ -99,6 +99,22 @@ check:
 	./check-readme.sh
 
 
+.PHONY: check-debian-release
+check-debian-release:
+	@for RELEASE in debian10 debian11; \
+	do \
+		ERRORS=$$(find .. -name molecule.yml \
+			! -path '*/.*/*' \
+			! -path '../tests/molecule.yml' \
+			-exec grep -L $$RELEASE {} \;) ;\
+		[ -z "$$ERRORS" ] || { \
+			echo "Missing test instance for: $$RELEASE"; \
+			echo "$$ERRORS"; \
+			RETCODE=199; \
+		}; \
+	done; \
+	[ -z "$$RETCODE" ] || exit $$RETCODE;
+
 include Makefile.venv
 Makefile.venv:
 	curl \
